# NOTE: This file is not a stand-alone package. It is part of
# a 'root' device template and expects the substitutions that
# are hereby referenced to be defined by its parent.

binary_sensor:
  #### B hold
  - platform: template
    name: "Hold B"
    id: hold_b
    publish_initial_state: true
  #### B double click  
  - platform: template
    name: "Double B"
    id: double_b
    publish_initial_state: true

  ###
  # Physical Button B
  - platform: gpio
    name: "Button B"
    id: button_b
    pin:
      number: ${button_b_gpio}
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true

    filters:
      - delayed_on: ${filter_delay_on}
      - delayed_off: ${filter_delay_off}

    on_multi_click:
      # single click detection
      - timing:
        - ${timing_click_1}
        - ${timing_click_2}
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: B
                gesture: single_click

      # double click detection
      - timing:
          - ${timing_double_click_1}
          - ${timing_double_click_2}
          - ${timing_double_click_3}
          - ${timing_double_click_4}
          ### Double b
          - binary_sensor.template.publish:
              id: double_b
              state: ON
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: B
                gesture: double_click
          - delay: 500ms
          - binary_sensor.template.publish:
              id: double_b
              state: OFF

      # hold detection
      - timing:
          - ${timing_hold}
        then:
          - while:
              condition:
                binary_sensor.is_on: button_b
              then:
                - light.toggle: led_status
                ### B Hold
                - binary_sensor.template.publish:
                    id: hold_b
                    state: ON
                ###
                - homeassistant.event:
                    event: esphome.on_gesture
                    data:
                      button: B
                      gesture: button_hold
                - delay: ${timing_hold_repeat}
          - binary_sensor.template.publish:
              id: hold_b
              state: OFF
          - light.turn_off: led_status
