# NOTE: This file is not a stand-alone package. It is part of
# a 'root' device template and expects the substitutions that
# are hereby referenced to be defined by its parent.

binary_sensor:
  #### C hold
  - platform: template
    name: "Hold C"
    id: hold_c
    publish_initial_state: true
  #### C double click  
  - platform: template
    name: "Double C"
    id: double_c
    publish_initial_state: true

  ###
  # Physical Button C
  - platform: gpio
    name: "Button C"
    id: button_c
    pin:
      number: ${button_c_gpio}
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true

    filters:
      - delayed_on: ${filter_delay_on}
      - delayed_off: ${filter_delay_off}
    
    on_multi_click:
      # single click detection
      - timing:
        - ${timing_click_1}
        - ${timing_click_2}
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: C
                gesture: single_click

      # double click detection
      - timing:
          - ${timing_double_click_1}
          - ${timing_double_click_2}
          - ${timing_double_click_3}
          - ${timing_double_click_4}
        then:
          ### Double C
          - binary_sensor.template.publish:
              id: double_c
              state: ON
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: C
                gesture: double_click
          - delay: 500ms
          - binary_sensor.template.publish:
              id: double_c
              state: OFF

      # hold detection
      - timing:
          - ${timing_hold}
        then:
          - while:
              condition:
                binary_sensor.is_on: button_c
              then:
                - light.toggle: led_status
                ### C Hold
                - binary_sensor.template.publish:
                    id: hold_c
                    state: ON
                ###
                - homeassistant.event:
                    event: esphome.on_gesture
                    data:
                      button: C
                      gesture: button_hold
                - delay: ${timing_hold_repeat}
          - binary_sensor.template.publish:
              id: hold_c
              state: OFF
          - light.turn_off: led_status
