# https://community.home-assistant.io/t/onboard-battery-level-of-this-esp32-voltage-divider-battery-level/326056/6
# https://wiki.seeedstudio.com/check_battery_voltage/
# https://community.home-assistant.io/t/esphome-battery-level-sensor/245196/19
#  VCC
#  |
#  R1 200k
#  |
#  ----> Vout -> ADC(GPIO)
#  |
#  R2 200k
#  |
#  GND
# 

sensor:
  - platform: adc
    id: batt_voltage
    icon: "mdi:lightning-bolt"
    pin: GPIO01
    attenuation: auto
    name: Battery Voltage
    entity_category: "diagnostic"
    update_interval: 5s
    accuracy_decimals: 3
    filters:
      - multiply: 2.0
      #use moving median to smooth spikes
      - median:
          window_size: 10
          send_every: 10
          send_first_at: 10
      - delta: 0.1 #Only send values to HA if they change 
      - throttle: 30s #Limit values sent to Ha

#Convert the Voltage to a battery  level (%)
  - platform: copy
    source_id: batt_voltage
    id: batt_level
    icon: "mdi:battery"
    name: Battery Level
    entity_category: "diagnostic"
    unit_of_measurement: '%'
    accuracy_decimals: 1
    filters:
      - calibrate_linear:
         method: exact
         datapoints:
          - 0.00 -> 0.0
          - 3.30 -> 1.0
          - 3.39 -> 10.0
          - 3.75 -> 50.0
          - 4.11 -> 90.0
          - 4.20 -> 100.0
      #Handle/cap boundaries
      - lambda: |
          if (x < 0) return 0; 
          else if (x > 100) return 100;
          else return (x);
      - delta: 0.5 #Only send values to HA if they change 
      - throttle: 30s #Limit values sent to Ha