output:
  - platform: gpio
    pin: GPIO44
    id: pwr_bme

i2c:
  sda: GPIO05
  scl: GPIO06
  scan: true
  id: i2cbus_bme

bme68x_bsec2_i2c:
  id: lib_bsec
  i2c_id: i2cbus_bme
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V

sensor:
  - platform: bme68x_bsec2
    bme68x_bsec2_id: lib_bsec
    temperature:
      name: "Temperature"
      web_server:
        sorting_group_id: sg_environment
    pressure:
      name: "Pressure"
      web_server:
        sorting_group_id: sg_environment
    humidity:
      name: "Humidity"
      web_server:
        sorting_group_id: sg_environment
    gas_resistance:
      name: "Gas Resistance"
      web_server:
        sorting_group_id: sg_environment
    iaq:
      name: "IAQ"
      id: iaq
      web_server:
        sorting_group_id: sg_environment
    co2_equivalent:
      name: "CO2"
      web_server:
        sorting_group_id: sg_environment
    breath_voc_equivalent:
      name: "Breath VOC"
      web_server:
        sorting_group_id: sg_environment

text_sensor:
  - platform: bme68x_bsec2
    iaq_accuracy:
      name: "IAQ Accuracy"
      web_server:
        sorting_group_id: sg_environment

  - platform: template
    name: "IAQ Status"
    icon: "mdi:checkbox-marked-circle-outline"
    web_server:
      sorting_group_id: sg_environment
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly Polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately Polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily Polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely Polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely Polluted"};
      }
      else {
        return {"Sensor Error!"};
      }