binary_sensor:
  - platform: gpio
    id: button_external
    internal: true
    pin:
      number: GPIO07
      mode:
        input: true
        pulldown: true
    filters:
      - delayed_on: 5s
    on_press:
      then:
        - button.press: button_restart
