substitutions:
  led_variant: "WS2811"
  led_count: "11"

light:
  - platform: neopixelbus
    type: GRB
    variant: ${led_variant}
    pin: GPIO02
    num_leds: ${led_count}
    name: "Light Strip"
    id: light_strip
    internal: true
