
#output:
#  - platform: template
#    type: float
#    id: color_sleep_r
#  - platform: template
#    type: float
#    id: color_sleep_g
#  - platform: template
#    type: float
#    id: color_sleep_b
#  - platform: template
#    type: float
#    id: color_wake_r
#  - platform: template
#    type: float
#    id: color_wake_g
#  - platform: template
#    type: float
#    id: color_wake_b

globals:
  - id: color_sleep_r
    type: float  

light:
  - platform: rgb
    name: "Sleep Time Color"
    entity_category: CONFIG
    web_server:
      sorting_group_id: sg_sleep
    red: color_sleep_r
    green: color_sleep_r
    blue: color_sleep_r
    restore_mode: RESTORE_DEFAULT_ON
    initial_state:
      brightness: 60%
      red: 100%
      green: 0%
      blue: 0%

  - platform: rgb
    name: "Wake Time Color"
    entity_category: CONFIG
    web_server:
      sorting_group_id: sg_sleep
    red: color_sleep_r
    green: color_sleep_r
    blue: color_sleep_r
    restore_mode: RESTORE_DEFAULT_ON
    initial_state:
      brightness: 60%
      red: 0%
      green: 100%
      blue: 0%

datetime:
  - platform: template
    id: sleep_start
    type: time
    name: "Bedtime Starts"
    entity_category: CONFIG
    icon: 'mdi:icon-moon'
    web_server:
      sorting_group_id: sg_sleep
    optimistic: yes
    initial_value: "19:00:00"
    restore_value: true

  - platform: template
    id: sleep_end
    type: time
    name: Bedtime Ends at"
    entity_category: CONFIG
    icon: 'mdi:icon-sun'
    web_server:
      sorting_group_id: sg_sleep
    optimistic: yes
    initial_value: "06:00:00"
    restore_value: true

  - platform: template
    id: wake_end
    type: time
    name: "Wakeup Ends at"
    entity_category: CONFIG
    icon: 'mdi:icon-star'
    web_server:
      sorting_group_id: sg_sleep
    optimistic: yes
    initial_value: "06:00:00"
    restore_value: true    