datetime:
  - platform: template
    id: sleep_start
    type: time
    name: Bedtime Starts at
    entity_category: CONFIG
    icon: 'mdi:weather-night'
    web_server:
      sorting_group_id: sg_schedule
      sorting_weight: 10
    optimistic: yes
    initial_value: "19:00:00"
    restore_value: true

  - platform: template
    id: sleep_end
    type: time
    name: Bedtime Ends at
    entity_category: CONFIG
    icon: 'mdi:sun-clock'
    web_server:
      sorting_group_id: sg_schedule
      sorting_weight: 20
    optimistic: yes
    initial_value: "06:00:00"
    restore_value: true

  - platform: template
    id: wake_end
    type: time
    name: Wakeup Ends at
    entity_category: CONFIG
    icon: 'mdi:clock-star-four-points-outline'
    web_server:
      sorting_group_id: sg_schedule
      sorting_weight: 30
    optimistic: yes
    initial_value: "06:30:00"
    restore_value: true

text_sensor:
  - platform: template
    id: schedule_sleeping_hours
    name: "Sleeping Hours"
    icon: "mdi:sun-clock"
    web_server:
      sorting_group_id: sg_schedule
      sorting_weight: 32
    entity_category: CONFIG

  - platform: template
    id: schedule_status
    name: "Schedule Status"
    icon: "mdi:sun-clock"
    web_server:
      sorting_group_id: sg_schedule
      sorting_weight: 34
    entity_category: CONFIG
    update_interval: 5s
    lambda: |-
      return
           id(schedule_status_code) == 0 ? {"Lamp Off"}
        :  id(schedule_status_code) == 1 ? {"Sleep Light On"}
        :  id(schedule_status_code) == 2 ? {"Wake Light On"}
        :  {"Unknown"};

light:
  - platform: rgb
    name: "Bedtime Light"
    id: sleep_light
    entity_category: CONFIG
    icon: "mdi:bed"
    web_server:
      sorting_group_id: sg_schedule
      sorting_weight: 40
    red: color_sleep_r
    green: color_sleep_g
    blue: color_sleep_b
    restore_mode: RESTORE_DEFAULT_ON
    initial_state:
      brightness: 60%
      red: 100%
      green: 0%
      blue: 0%

  - platform: rgb
    name: "Wakeup Light"
    id: wake_light
    entity_category: CONFIG
    icon: "mdi:white-balance-sunny"
    web_server:
      sorting_group_id: sg_schedule
      sorting_weight: 50
    red: color_wake_r
    green: color_wake_g
    blue: color_wake_b
    restore_mode: RESTORE_DEFAULT_ON
    initial_state:
      brightness: 60%
      red: 0%
      green: 100%
      blue: 0%
